version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=laundrydb

  frontend: 
    build: ./frontend
    ports:
      - "8081:3000"

  db:
    image: postgres:14
    environment:  
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laundrydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
